export const QUESTION_TYPES = {
  IGCSE: {
    SUMMARY: {
      id: 'igcse_summary',
      name: 'Summary',
      description: 'Condensing key information from texts',
      category: 'IGCSE',
      requiresMarkScheme: true,
      icon: '📄',
      color: '#3b82f6',
      wordLimit: 700,
    },
    NARRATIVE: {
      id: 'igcse_narrative',
      name: 'Narrative',
      description: 'Creative storytelling and structure',
      category: 'IGCSE',
      requiresMarkScheme: false,
      icon: '📖',
      color: '#8b5cf6',
      wordLimit: 700,
    },
    DESCRIPTIVE: {
      id: 'igcse_descriptive',
      name: 'Descriptive',
      description: 'Vivid imagery and atmospheric writing',
      category: 'IGCSE',
      requiresMarkScheme: false,
      icon: '🖼️',
      color: '#22c55e',
      wordLimit: 700,
    },
    WRITERS_EFFECT: {
      id: 'igcse_writers_effect',
      name: "Writer's Effect",
      description: 'Language analysis and impact',
      category: 'IGCSE',
      requiresMarkScheme: false,
      icon: '⚡',
      color: '#f59e42',
      wordLimit: 700,
    },
    DIRECTED_WRITING: {
      id: 'igcse_directed_writing',
      name: 'Directed Writing',
      description: 'Structured response to specific prompts',
      category: 'IGCSE',
      requiresMarkScheme: true,
      icon: '✍️',
      color: '#6366f1',
      wordLimit: 700,
    },
  },
  A_LEVEL: {
    ARGUMENTATIVE: {
      id: 'alevel_argumentative',
      name: 'Argumentative',
      description: 'Persuasive writing with evidence',
      category: 'A-Level',
      requiresMarkScheme: true,
      icon: '🎯',
      color: '#ef4444',
      wordLimit: 1400,
    },
    ANALYTICAL: {
      id: 'alevel_analytical',
      name: 'Analytical',
      description: 'Critical analysis and evaluation',
      category: 'A-Level',
      requiresMarkScheme: true,
      icon: '🔍',
      color: '#06b6d4',
      wordLimit: 1400,
    },
    COMPARATIVE: {
      id: 'alevel_comparative',
      name: 'Comparative',
      description: 'Comparing and contrasting ideas',
      category: 'A-Level',
      requiresMarkScheme: true,
      icon: '⚖️',
      color: '#8b5cf6',
      wordLimit: 1400,
    },
    CREATIVE: {
      id: 'alevel_creative',
      name: 'Creative',
      description: 'Imaginative and original writing',
      category: 'A-Level',
      requiresMarkScheme: false,
      icon: '✨',
      color: '#f59e42',
      wordLimit: 1400,
    },
  },
};

export const QUESTION_CATEGORIES = {
  IGCSE: 'IGCSE',
  A_LEVEL: 'A-Level',
};

export default QUESTION_TYPES;
